### ISSUE TITLE
Problem while running

### ISSUE THREAD

**Issue by susheel-selvamani** [tito/kivy-gmaps#8]
This is the error when I try to run the main.py. Please do try to help me with this.

#############
[ERROR  ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kivy/logger.py", line 225, in emit
    self._configure()
  File "/usr/lib/python3/dist-packages/kivy/logger.py", line 183, in _configure
    FileHandler.fd = open(filename, 'w')
PermissionError: [Errno 13] Permission denied: '/home/susheel/.kivy/logs/kivy_17-09-19_0.txt'
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "/home/susheel/Downloads/kivy-gmaps-master/main.py", line 6, in <module>
     from gmaps import GMap, run_on_ui_thread
   File "/home/susheel/Downloads/kivy-gmaps-master/gmaps/__init__.py", line 29, in <module>
     from android.runnable import run_on_ui_thread
 ImportError: No module named 'android'

**Comment by MAnand59** [comment]
i am having the same issue does anyone know a fix then please let me know...

**Comment by moonpyx** [comment]
Hi, in you file .spec of buildozer add in requirements module android
